name: scraper

on:
  schedule:
    - cron: '*/5 * * * *'

env:
  NODE_ENV: production
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  scrape:
    name: Update awesome profiles
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.1
      - run: npm i
      - run: npm run migration
      - uses: stefanzweifel/git-auto-commit-action@v4.4.0
        with:
          commit_message: Update readme awesome profiles
          branch: master
  waka-readme:
    name: Update Readme with Metrics
    needs: [scrape]
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
